### ISSUE TITLE
Larger QR

### ISSUE THREAD

**Issue by electr1fy0** [EETagent/Send#2]
Would be great if you could reposition stuff such that the QR is bigger and easier to scan, possibly by truncating the link and stuff.

**Comment by EETagent** [comment]
Hello, thanks for creating an issue, what is your screen resolution? It's pretty big on 2560 × 1600, should be enough for effortless scanning.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/20557318/201158658-773858b3-dcfe-4761-97a7-10e6e2960e96.png">

**Comment by electr1fy0** [comment]
My screen resolution is the same as yours.
I just feel the UI could be redesigned a bit to make the QR easier to scan as there's plenty of unused space.
